# Generated by Django 5.0.7 on 2024-08-01 00:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('procedimentos', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimentos.procedimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.sala')),
            ],
            options={
                'unique_together': {('profissional', 'sala', 'data_horario')},
            },
        ),
    ]
